server {
    listen 8080;

    server_name _;

    location /sub/ {

        proxy_pass https://pasarguard.lexum.sbs:8000/sub/;

        proxy_ssl_server_name on;
        proxy_ssl_name pasarguard.lexum.sbs;

        proxy_set_header Host pasarguard.lexum.sbs;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept $http_accept;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_buffering off;
        proxy_request_buffering off;
    }
}
